services:
  backend:
    build: ./backend
    image: shopbag-backend
    restart: unless-stopped
    ports:
      - 5000:5000
    networks:
      - shop-app
    volumes:
      - ./backend:/app
      - /app/node_modules
  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_STRIPE_KEY=$REACT_APP_STRIPE_KEY
    image: shopbag-frontend
    ports:
      - 3000:80
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - shop-app
    volumes:
      - ./frontend/src:/app/src

networks:
  shop-app:
      
  
